:barbarian: glyphicon-warning-sign
:bard: glyphicon-comment
:cleric: glyphicon-heart
:druid: glyphicon-tree-conifer
:fighter: glyphicon-tower
:monk: glyphicon-cloud-upload
:paladin: glyphicon-plus-sign
:ranger: glyphicon-screenshot
:rogue: glyphicon-eye-close
:sorcerer: glyphicon-fire
:wizard: glyphicon-flash
